### ISSUE TITLE
Plugin is not installed

### ISSUE THREAD

**Issue by WebVPF** [wintercms/wn-search-plugin#1] opened 2022-05-05 10:45 UTC
The plugin is not installed.

Console message:
![2022-05-05_083858](https://user-images.githubusercontent.com/61043464/166905783-5d6ff609-4cb4-41f9-8fab-d4d1d3df26b1.jpg)

Winter CMS 1.1.8
PHP 8.0 (before that was php 7.4)
Composer version 2.0.11

**Comment by bennothommo** [comment] 2022-05-05 12:04
I wouldn't use this plugin yet. It's public, but it's not ready. :)

**Comment by bennothommo** [comment] 2022-05-09 06:47
@WebVPF I'm pretty close to finalising this plugin. Would you be able to post your `composer.json` if possible - I just wanna see what might be clashing with this plugin?

**Comment by bennothommo** [comment] 2022-05-09 06:52
Never mind - the problem is because we are targeting Laravel Scout 9, which requires Laravel 8 or 9, but Winter CMS 1.1 only supports Laravel 6. From what I can tell, we can easily support Laravel Scout 8 which still works with Laravel 6.

**Comment by bennothommo** [comment] 2022-05-09 06:55
Fixed by f8a74b7e7cb6fb7b144543853a3e296022934bb3

**Closed by bennothommo** 2022-05-09 06:55 UTC

**Comment by WebVPF** [comment] 2022-05-09 08:35
@bennothommo The error has changed. Plugin is not installed.

```
composer require winter/wn-search-plugin
```
![2022-05-09_112136](https://user-images.githubusercontent.com/61043464/167371044-e8b74ea7-0ce5-42fa-a223-244070510d81.jpg)

composer.json
```
{
    "name": "wintercms/winter",
    "description": "Free, open-source, self-hosted CMS platform based on the Laravel PHP Framework. Originally known as October CMS.",
    "homepage": "https://wintercms.com",
    "type": "project",
    "keywords": ["winter", "cms", "wintercms", "laravel", "cmf"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Original Author"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Original Author"
        },
        {
            "name": "Luke Towers",
            "email": "wintercms@luketowers.ca",
            "role": "Lead Maintainer"
        }
    ],
    "support": {
        "issues": "https://github.com/wintercms/winter/issues",
        "docs": "https://wintercms.github.io/docs/",
        "discord": "https://discord.gg/D5MFSPH6Ux",
        "source": "https://github.com/wintercms/winter"
    },
    "require": {
        "php": ">=7.2.9",
        "winter/storm": "~1.1.2",
        "winter/wn-system-module": "~1.1.2",
        "winter/wn-backend-module": "~1.1.2",
        "winter/wn-cms-module": "~1.1.2",
        "laravel/framework": "~6.0",
        "wikimedia/composer-merge-plugin": "~2.0.1",
        "webvpf/wn-darkbackend-plugin": "^1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^8.4|^9.3.3",
        "mockery/mockery": "~1.3.3|^1.4.2",
        "fakerphp/faker": "~1.9",
        "squizlabs/php_codesniffer": "3.*",
        "php-parallel-lint/php-parallel-lint": "^1.0",
        "dms/phpunit-arraysubset-asserts": "^0.1.0|^0.2.1"
    },
    "autoload-dev": {
        "classmap": [
            "tests/concerns/InteractsWithAuthentication.php",
            "tests/fixtures/backend/models/UserFixture.php",
            "tests/TestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate",
            "php artisan package:discover"
        ],
        "post-update-cmd": [
            "php artisan winter:version",
            "php artisan package:discover"
        ],
        "test": [
            "phpunit --stop-on-failure"
        ],
        "lint": [
            "parallel-lint --exclude vendor --exclude storage --exclude tests/fixtures/plugins/testvendor/goto/Plugin.php ."
        ],
        "sniff": [
            "phpcs --colors -nq --report=\"full\" --extensions=\"php\""
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}

```

**Comment by bennothommo** [comment] 2022-05-09 08:42
Darn, I was relying on the changelog being accurate. It seems that due to some commands and functionality we are using (mainly with respect to managing search indexes), we can only target Scout 9, which means that this plugin will only work with Winter 1.2.
